version: "3"

services:
  neutron-landingpage:
    build:
      context: .
    container_name: neutron-landingpage
    image: registry.hugosoft.dev/hugosoft/neutron-landingpage:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_NEUTRON_WEB=https://neutron-robotics.com
      - NEXT_PUBLIC_NEUTRON_APPLICATION=https://app.neutron-robotics.com
      - NEXT_PUBLIC_NEUTRON_API=https://api.neutron-robotics.com
      - NEXT_PUBLIC_NEUTRON_DOCS=https://docs.neutron-robotics.com
    ports:
      - "22300:3000"