version: "3"

services:
  neutron-landingpage:
    build:
      context: .
    container_name: neutron-landingpage
    image: neutron-landingpage-1
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"