version: "3"

services:
  neutron-landingpage:
    build:
      context: .
    container_name: neutron-landingpage
    image: registry.hugosoft.dev/hugosoft/neutron-landingpage:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "22300:3000"