version: "3"

services:
  neutron-documentation:
    build:
      context: .
    container_name: neutron-documentation
    image: registry.hugosoft.dev/hugosoft/neutron-documentation:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "22301:4000"