name: Neutron landingpage build CI

on: [push]

jobs:
  buildDocs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
      - run: |
          cd ./docs
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildLandingPage:
    runs-on: ubuntu-latest
    name: Build Landing Page
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
      - run: |
          cd ./home
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}